// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: arbeiter.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createArbeiter = `-- name: CreateArbeiter :one
INSERT INTO arbeiter (id, name, email, passwort_hash, rolle, wochenstunden, stundenlohn, aktiv)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, email, passwort_hash, rolle, wochenstunden, stundenlohn, aktiv, created_at, updated_at
`

type CreateArbeiterParams struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Email         string    `json:"email"`
	PasswortHash  string    `json:"passwort_hash"`
	Rolle         string    `json:"rolle"`
	Wochenstunden string    `json:"wochenstunden"`
	Stundenlohn   string    `json:"stundenlohn"`
	Aktiv         bool      `json:"aktiv"`
}

func (q *Queries) CreateArbeiter(ctx context.Context, arg CreateArbeiterParams) (Arbeiter, error) {
	row := q.db.QueryRow(ctx, createArbeiter,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswortHash,
		arg.Rolle,
		arg.Wochenstunden,
		arg.Stundenlohn,
		arg.Aktiv,
	)
	var i Arbeiter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswortHash,
		&i.Rolle,
		&i.Wochenstunden,
		&i.Stundenlohn,
		&i.Aktiv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArbeiterByEmail = `-- name: GetArbeiterByEmail :one
SELECT id, name, email, passwort_hash, rolle, wochenstunden, stundenlohn, aktiv, created_at, updated_at FROM arbeiter WHERE email = $1
`

func (q *Queries) GetArbeiterByEmail(ctx context.Context, email string) (Arbeiter, error) {
	row := q.db.QueryRow(ctx, getArbeiterByEmail, email)
	var i Arbeiter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswortHash,
		&i.Rolle,
		&i.Wochenstunden,
		&i.Stundenlohn,
		&i.Aktiv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArbeiterByID = `-- name: GetArbeiterByID :one
SELECT id, name, email, passwort_hash, rolle, wochenstunden, stundenlohn, aktiv, created_at, updated_at FROM arbeiter WHERE id = $1
`

func (q *Queries) GetArbeiterByID(ctx context.Context, id uuid.UUID) (Arbeiter, error) {
	row := q.db.QueryRow(ctx, getArbeiterByID, id)
	var i Arbeiter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswortHash,
		&i.Rolle,
		&i.Wochenstunden,
		&i.Stundenlohn,
		&i.Aktiv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdmin = `-- name: UpsertAdmin :one
INSERT INTO arbeiter (id, name, email, passwort_hash, rolle, aktiv)
VALUES ($1, $2, $3, $4, 'admin', true)
ON CONFLICT (email) DO UPDATE
   SET name = EXCLUDED.name,
       passwort_hash = EXCLUDED.passwort_hash,
       rolle = 'admin',
       aktiv = true,
       updated_at = now()
RETURNING id, name, email, passwort_hash, rolle, wochenstunden, stundenlohn, aktiv, created_at, updated_at
`

type UpsertAdminParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswortHash string    `json:"passwort_hash"`
}

// Idempotenter Seed: legt den Inhaber an oder aktualisiert Name/Passwort, falls die E-Mail existiert.
func (q *Queries) UpsertAdmin(ctx context.Context, arg UpsertAdminParams) (Arbeiter, error) {
	row := q.db.QueryRow(ctx, upsertAdmin,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswortHash,
	)
	var i Arbeiter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswortHash,
		&i.Rolle,
		&i.Wochenstunden,
		&i.Stundenlohn,
		&i.Aktiv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
