// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: baustelle.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBaustelle = `-- name: CreateBaustelle :one
INSERT INTO baustelle (id, name, adresse, aktiv)
VALUES ($1, $2, $3, $4)
RETURNING id, name, adresse, aktiv, created_at, updated_at
`

type CreateBaustelleParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Adresse string    `json:"adresse"`
	Aktiv   bool      `json:"aktiv"`
}

func (q *Queries) CreateBaustelle(ctx context.Context, arg CreateBaustelleParams) (Baustelle, error) {
	row := q.db.QueryRow(ctx, createBaustelle,
		arg.ID,
		arg.Name,
		arg.Adresse,
		arg.Aktiv,
	)
	var i Baustelle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Adresse,
		&i.Aktiv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateBaustelle = `-- name: DeactivateBaustelle :one
UPDATE baustelle
   SET aktiv = false, updated_at = now()
 WHERE id = $1
RETURNING id, name, adresse, aktiv, created_at, updated_at
`

// Soft-Delete: idempotent (mehrfaches Deaktivieren ändert nur updated_at).
func (q *Queries) DeactivateBaustelle(ctx context.Context, id uuid.UUID) (Baustelle, error) {
	row := q.db.QueryRow(ctx, deactivateBaustelle, id)
	var i Baustelle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Adresse,
		&i.Aktiv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBaustelleByID = `-- name: GetBaustelleByID :one
SELECT id, name, adresse, aktiv, created_at, updated_at FROM baustelle WHERE id = $1
`

func (q *Queries) GetBaustelleByID(ctx context.Context, id uuid.UUID) (Baustelle, error) {
	row := q.db.QueryRow(ctx, getBaustelleByID, id)
	var i Baustelle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Adresse,
		&i.Aktiv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBaustellen = `-- name: ListBaustellen :many
SELECT id, name, adresse, aktiv, created_at, updated_at FROM baustelle
WHERE ($1::boolean IS NULL OR aktiv = $1::boolean)
ORDER BY name ASC, created_at ASC
`

// Optionaler aktiv-Filter: NULL => alle. Stabile Sortierung nach Name.
func (q *Queries) ListBaustellen(ctx context.Context, aktiv *bool) ([]Baustelle, error) {
	rows, err := q.db.Query(ctx, listBaustellen, aktiv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Baustelle
	for rows.Next() {
		var i Baustelle
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Adresse,
			&i.Aktiv,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBaustelle = `-- name: UpdateBaustelle :one
UPDATE baustelle
   SET name       = COALESCE($1::text, name),
       adresse    = COALESCE($2::text, adresse),
       aktiv      = COALESCE($3::boolean, aktiv),
       updated_at = now()
 WHERE id = $4
RETURNING id, name, adresse, aktiv, created_at, updated_at
`

type UpdateBaustelleParams struct {
	Name    *string   `json:"name"`
	Adresse *string   `json:"adresse"`
	Aktiv   *bool     `json:"aktiv"`
	ID      uuid.UUID `json:"id"`
}

// Partial update: nur gesetzte (non-NULL) Felder werden geändert (COALESCE).
func (q *Queries) UpdateBaustelle(ctx context.Context, arg UpdateBaustelleParams) (Baustelle, error) {
	row := q.db.QueryRow(ctx, updateBaustelle,
		arg.Name,
		arg.Adresse,
		arg.Aktiv,
		arg.ID,
	)
	var i Baustelle
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Adresse,
		&i.Aktiv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
