// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dokument.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const adminListDokument = `-- name: AdminListDokument :many
SELECT id, arbeiter_id, typ, jahr, monat, dateiname, storage_key, mime_type, groesse, created_at FROM dokument
WHERE ($1::uuid IS NULL OR arbeiter_id = $1::uuid)
ORDER BY created_at DESC
`

func (q *Queries) AdminListDokument(ctx context.Context, arbeiterID *uuid.UUID) ([]Dokument, error) {
	rows, err := q.db.Query(ctx, adminListDokument, arbeiterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dokument
	for rows.Next() {
		var i Dokument
		if err := rows.Scan(
			&i.ID,
			&i.ArbeiterID,
			&i.Typ,
			&i.Jahr,
			&i.Monat,
			&i.Dateiname,
			&i.StorageKey,
			&i.MimeType,
			&i.Groesse,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDokument = `-- name: CreateDokument :one
INSERT INTO dokument (id, arbeiter_id, typ, jahr, monat, dateiname, storage_key, mime_type, groesse)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, arbeiter_id, typ, jahr, monat, dateiname, storage_key, mime_type, groesse, created_at
`

type CreateDokumentParams struct {
	ID         uuid.UUID `json:"id"`
	ArbeiterID uuid.UUID `json:"arbeiter_id"`
	Typ        string    `json:"typ"`
	Jahr       int32     `json:"jahr"`
	Monat      int32     `json:"monat"`
	Dateiname  string    `json:"dateiname"`
	StorageKey string    `json:"storage_key"`
	MimeType   string    `json:"mime_type"`
	Groesse    int64     `json:"groesse"`
}

func (q *Queries) CreateDokument(ctx context.Context, arg CreateDokumentParams) (Dokument, error) {
	row := q.db.QueryRow(ctx, createDokument,
		arg.ID,
		arg.ArbeiterID,
		arg.Typ,
		arg.Jahr,
		arg.Monat,
		arg.Dateiname,
		arg.StorageKey,
		arg.MimeType,
		arg.Groesse,
	)
	var i Dokument
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.Typ,
		&i.Jahr,
		&i.Monat,
		&i.Dateiname,
		&i.StorageKey,
		&i.MimeType,
		&i.Groesse,
		&i.CreatedAt,
	)
	return i, err
}

const getDokumentByID = `-- name: GetDokumentByID :one
SELECT id, arbeiter_id, typ, jahr, monat, dateiname, storage_key, mime_type, groesse, created_at FROM dokument WHERE id = $1
`

func (q *Queries) GetDokumentByID(ctx context.Context, id uuid.UUID) (Dokument, error) {
	row := q.db.QueryRow(ctx, getDokumentByID, id)
	var i Dokument
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.Typ,
		&i.Jahr,
		&i.Monat,
		&i.Dateiname,
		&i.StorageKey,
		&i.MimeType,
		&i.Groesse,
		&i.CreatedAt,
	)
	return i, err
}

const listOwnDokument = `-- name: ListOwnDokument :many
SELECT id, arbeiter_id, typ, jahr, monat, dateiname, storage_key, mime_type, groesse, created_at FROM dokument WHERE arbeiter_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOwnDokument(ctx context.Context, arbeiterID uuid.UUID) ([]Dokument, error) {
	rows, err := q.db.Query(ctx, listOwnDokument, arbeiterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dokument
	for rows.Next() {
		var i Dokument
		if err := rows.Scan(
			&i.ID,
			&i.ArbeiterID,
			&i.Typ,
			&i.Jahr,
			&i.Monat,
			&i.Dateiname,
			&i.StorageKey,
			&i.MimeType,
			&i.Groesse,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
