// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT 1 AS ok
`

// Placeholder so sqlc has at least one query to generate from in Phase 1
// (sqlc errors on an empty queries dir). Replace/extend with real queries in Phase 2.
func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
