// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Arbeiter struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Email         string    `json:"email"`
	PasswortHash  string    `json:"passwort_hash"`
	Rolle         string    `json:"rolle"`
	Wochenstunden string    `json:"wochenstunden"`
	Stundenlohn   string    `json:"stundenlohn"`
	Aktiv         bool      `json:"aktiv"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Baustelle struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Adresse   string    `json:"adresse"`
	Aktiv     bool      `json:"aktiv"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RefreshToken struct {
	ID         uuid.UUID  `json:"id"`
	ArbeiterID uuid.UUID  `json:"arbeiter_id"`
	TokenHash  []byte     `json:"token_hash"`
	ExpiresAt  time.Time  `json:"expires_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Zeitbuchung struct {
	ID           uuid.UUID  `json:"id"`
	ArbeiterID   uuid.UUID  `json:"arbeiter_id"`
	BaustelleID  *uuid.UUID `json:"baustelle_id"`
	StartZeit    time.Time  `json:"start_zeit"`
	EndZeit      *time.Time `json:"end_zeit"`
	PauseMinuten int32      `json:"pause_minuten"`
	Notiz        string     `json:"notiz"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}
