// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_token (id, arbeiter_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, arbeiter_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	ID         uuid.UUID `json:"id"`
	ArbeiterID uuid.UUID `json:"arbeiter_id"`
	TokenHash  []byte    `json:"token_hash"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.ArbeiterID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, arbeiter_id, token_hash, expires_at, revoked_at, created_at FROM refresh_token WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensForArbeiter = `-- name: RevokeAllRefreshTokensForArbeiter :exec
UPDATE refresh_token
   SET revoked_at = now()
 WHERE arbeiter_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensForArbeiter(ctx context.Context, arbeiterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForArbeiter, arbeiterID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_token
   SET revoked_at = now()
 WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}
