// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urlaubsantrag.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminListUrlaubsantrag = `-- name: AdminListUrlaubsantrag :many
SELECT id, arbeiter_id, von_datum, bis_datum, typ, status, grund, entschieden_von, entschieden_am, created_at FROM urlaubsantrag
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::date    IS NULL OR von_datum >= $2::date)
  AND ($3::date    IS NULL OR von_datum <= $3::date)
ORDER BY created_at DESC
`

type AdminListUrlaubsantragParams struct {
	Status *string    `json:"status"`
	Von    *time.Time `json:"von"`
	Bis    *time.Time `json:"bis"`
}

// Optionale Filter: status, Zeitraum über von_datum. Neueste Anträge zuerst.
func (q *Queries) AdminListUrlaubsantrag(ctx context.Context, arg AdminListUrlaubsantragParams) ([]Urlaubsantrag, error) {
	rows, err := q.db.Query(ctx, adminListUrlaubsantrag, arg.Status, arg.Von, arg.Bis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Urlaubsantrag
	for rows.Next() {
		var i Urlaubsantrag
		if err := rows.Scan(
			&i.ID,
			&i.ArbeiterID,
			&i.VonDatum,
			&i.BisDatum,
			&i.Typ,
			&i.Status,
			&i.Grund,
			&i.EntschiedenVon,
			&i.EntschiedenAm,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUrlaubsantrag = `-- name: CreateUrlaubsantrag :one
INSERT INTO urlaubsantrag (id, arbeiter_id, von_datum, bis_datum, typ, grund)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, arbeiter_id, von_datum, bis_datum, typ, status, grund, entschieden_von, entschieden_am, created_at
`

type CreateUrlaubsantragParams struct {
	ID         uuid.UUID `json:"id"`
	ArbeiterID uuid.UUID `json:"arbeiter_id"`
	VonDatum   time.Time `json:"von_datum"`
	BisDatum   time.Time `json:"bis_datum"`
	Typ        string    `json:"typ"`
	Grund      string    `json:"grund"`
}

// status defaultet auf 'offen'.
func (q *Queries) CreateUrlaubsantrag(ctx context.Context, arg CreateUrlaubsantragParams) (Urlaubsantrag, error) {
	row := q.db.QueryRow(ctx, createUrlaubsantrag,
		arg.ID,
		arg.ArbeiterID,
		arg.VonDatum,
		arg.BisDatum,
		arg.Typ,
		arg.Grund,
	)
	var i Urlaubsantrag
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.VonDatum,
		&i.BisDatum,
		&i.Typ,
		&i.Status,
		&i.Grund,
		&i.EntschiedenVon,
		&i.EntschiedenAm,
		&i.CreatedAt,
	)
	return i, err
}

const decideUrlaubsantrag = `-- name: DecideUrlaubsantrag :one
UPDATE urlaubsantrag
   SET status          = $1::text,
       entschieden_von = $2::uuid,
       entschieden_am  = now()
 WHERE id = $3 AND status = 'offen'
RETURNING id, arbeiter_id, von_datum, bis_datum, typ, status, grund, entschieden_von, entschieden_am, created_at
`

type DecideUrlaubsantragParams struct {
	Status         string    `json:"status"`
	EntschiedenVon uuid.UUID `json:"entschieden_von"`
	ID             uuid.UUID `json:"id"`
}

// Genehmigen/Ablehnen. Übergang nur aus 'offen' (atomar via WHERE).
func (q *Queries) DecideUrlaubsantrag(ctx context.Context, arg DecideUrlaubsantragParams) (Urlaubsantrag, error) {
	row := q.db.QueryRow(ctx, decideUrlaubsantrag, arg.Status, arg.EntschiedenVon, arg.ID)
	var i Urlaubsantrag
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.VonDatum,
		&i.BisDatum,
		&i.Typ,
		&i.Status,
		&i.Grund,
		&i.EntschiedenVon,
		&i.EntschiedenAm,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUrlaubsantrag = `-- name: DeleteUrlaubsantrag :exec
DELETE FROM urlaubsantrag
WHERE id = $1 AND arbeiter_id = $2
`

type DeleteUrlaubsantragParams struct {
	ID         uuid.UUID `json:"id"`
	ArbeiterID uuid.UUID `json:"arbeiter_id"`
}

// Handler stellt sicher, dass status = 'offen' ist (Get-first).
func (q *Queries) DeleteUrlaubsantrag(ctx context.Context, arg DeleteUrlaubsantragParams) error {
	_, err := q.db.Exec(ctx, deleteUrlaubsantrag, arg.ID, arg.ArbeiterID)
	return err
}

const getUrlaubsantragByID = `-- name: GetUrlaubsantragByID :one
SELECT id, arbeiter_id, von_datum, bis_datum, typ, status, grund, entschieden_von, entschieden_am, created_at FROM urlaubsantrag WHERE id = $1
`

// Admin: jeder Antrag.
func (q *Queries) GetUrlaubsantragByID(ctx context.Context, id uuid.UUID) (Urlaubsantrag, error) {
	row := q.db.QueryRow(ctx, getUrlaubsantragByID, id)
	var i Urlaubsantrag
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.VonDatum,
		&i.BisDatum,
		&i.Typ,
		&i.Status,
		&i.Grund,
		&i.EntschiedenVon,
		&i.EntschiedenAm,
		&i.CreatedAt,
	)
	return i, err
}

const getUrlaubsantragByIDForArbeiter = `-- name: GetUrlaubsantragByIDForArbeiter :one
SELECT id, arbeiter_id, von_datum, bis_datum, typ, status, grund, entschieden_von, entschieden_am, created_at FROM urlaubsantrag
WHERE id = $1 AND arbeiter_id = $2
`

type GetUrlaubsantragByIDForArbeiterParams struct {
	ID         uuid.UUID `json:"id"`
	ArbeiterID uuid.UUID `json:"arbeiter_id"`
}

// Ownership-Scope (Arbeiter).
func (q *Queries) GetUrlaubsantragByIDForArbeiter(ctx context.Context, arg GetUrlaubsantragByIDForArbeiterParams) (Urlaubsantrag, error) {
	row := q.db.QueryRow(ctx, getUrlaubsantragByIDForArbeiter, arg.ID, arg.ArbeiterID)
	var i Urlaubsantrag
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.VonDatum,
		&i.BisDatum,
		&i.Typ,
		&i.Status,
		&i.Grund,
		&i.EntschiedenVon,
		&i.EntschiedenAm,
		&i.CreatedAt,
	)
	return i, err
}

const listGenehmigteAbwesenheit = `-- name: ListGenehmigteAbwesenheit :many
SELECT arbeiter_id, von_datum, bis_datum FROM urlaubsantrag
WHERE status = 'genehmigt'
  AND typ IN ('urlaub', 'krankheit')
  AND von_datum <= $1::date
  AND bis_datum >= $2::date
  AND ($3::uuid IS NULL OR arbeiter_id = $3::uuid)
`

type ListGenehmigteAbwesenheitParams struct {
	Bis        time.Time  `json:"bis"`
	Von        time.Time  `json:"von"`
	ArbeiterID *uuid.UUID `json:"arbeiter_id"`
}

type ListGenehmigteAbwesenheitRow struct {
	ArbeiterID uuid.UUID `json:"arbeiter_id"`
	VonDatum   time.Time `json:"von_datum"`
	BisDatum   time.Time `json:"bis_datum"`
}

// Genehmigte Urlaube/Krankmeldungen, die sich mit [von, bis] überschneiden.
// Für die Überstunden-Berechnung (Phase 6): diese Tage gelten als Soll erfüllt.
func (q *Queries) ListGenehmigteAbwesenheit(ctx context.Context, arg ListGenehmigteAbwesenheitParams) ([]ListGenehmigteAbwesenheitRow, error) {
	rows, err := q.db.Query(ctx, listGenehmigteAbwesenheit, arg.Bis, arg.Von, arg.ArbeiterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenehmigteAbwesenheitRow
	for rows.Next() {
		var i ListGenehmigteAbwesenheitRow
		if err := rows.Scan(&i.ArbeiterID, &i.VonDatum, &i.BisDatum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnUrlaubsantrag = `-- name: ListOwnUrlaubsantrag :many
SELECT id, arbeiter_id, von_datum, bis_datum, typ, status, grund, entschieden_von, entschieden_am, created_at FROM urlaubsantrag
WHERE arbeiter_id = $1
ORDER BY von_datum DESC
`

func (q *Queries) ListOwnUrlaubsantrag(ctx context.Context, arbeiterID uuid.UUID) ([]Urlaubsantrag, error) {
	rows, err := q.db.Query(ctx, listOwnUrlaubsantrag, arbeiterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Urlaubsantrag
	for rows.Next() {
		var i Urlaubsantrag
		if err := rows.Scan(
			&i.ID,
			&i.ArbeiterID,
			&i.VonDatum,
			&i.BisDatum,
			&i.Typ,
			&i.Status,
			&i.Grund,
			&i.EntschiedenVon,
			&i.EntschiedenAm,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
