// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zeitbuchung.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminListZeitbuchung = `-- name: AdminListZeitbuchung :many
SELECT id, arbeiter_id, baustelle_id, start_zeit, end_zeit, pause_minuten, notiz, created_at, updated_at FROM zeitbuchung
WHERE ($1::uuid  IS NULL OR arbeiter_id  = $1::uuid)
  AND ($2::uuid IS NULL OR baustelle_id = $2::uuid)
  AND ($3::timestamptz   IS NULL OR start_zeit  >= $3::timestamptz)
  AND ($4::timestamptz   IS NULL OR start_zeit  <  $4::timestamptz)
ORDER BY start_zeit DESC
`

type AdminListZeitbuchungParams struct {
	ArbeiterID  *uuid.UUID `json:"arbeiter_id"`
	BaustelleID *uuid.UUID `json:"baustelle_id"`
	Von         *time.Time `json:"von"`
	Bis         *time.Time `json:"bis"`
}

// Admin-weite Liste mit optionalen Filtern. Neueste zuerst.
func (q *Queries) AdminListZeitbuchung(ctx context.Context, arg AdminListZeitbuchungParams) ([]Zeitbuchung, error) {
	rows, err := q.db.Query(ctx, adminListZeitbuchung,
		arg.ArbeiterID,
		arg.BaustelleID,
		arg.Von,
		arg.Bis,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zeitbuchung
	for rows.Next() {
		var i Zeitbuchung
		if err := rows.Scan(
			&i.ID,
			&i.ArbeiterID,
			&i.BaustelleID,
			&i.StartZeit,
			&i.EndZeit,
			&i.PauseMinuten,
			&i.Notiz,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSumZeitbuchung = `-- name: AdminSumZeitbuchung :one
SELECT
    COALESCE(SUM(
        CAST(EXTRACT(EPOCH FROM (end_zeit - start_zeit)) / 60 AS integer) - pause_minuten
    ), 0)::bigint AS summe_minuten,
    COUNT(*)::bigint AS anzahl
FROM zeitbuchung
WHERE end_zeit IS NOT NULL
  AND ($1::uuid  IS NULL OR arbeiter_id  = $1::uuid)
  AND ($2::uuid IS NULL OR baustelle_id = $2::uuid)
  AND ($3::timestamptz   IS NULL OR start_zeit  >= $3::timestamptz)
  AND ($4::timestamptz   IS NULL OR start_zeit  <  $4::timestamptz)
`

type AdminSumZeitbuchungParams struct {
	ArbeiterID  *uuid.UUID `json:"arbeiter_id"`
	BaustelleID *uuid.UUID `json:"baustelle_id"`
	Von         *time.Time `json:"von"`
	Bis         *time.Time `json:"bis"`
}

type AdminSumZeitbuchungRow struct {
	SummeMinuten int64 `json:"summe_minuten"`
	Anzahl       int64 `json:"anzahl"`
}

// Gesamtsumme der abgeschlossenen Dauer (Minuten) für die gefilterte Menge.
// Laufende Buchungen (end_zeit NULL) zählen nicht mit.
func (q *Queries) AdminSumZeitbuchung(ctx context.Context, arg AdminSumZeitbuchungParams) (AdminSumZeitbuchungRow, error) {
	row := q.db.QueryRow(ctx, adminSumZeitbuchung,
		arg.ArbeiterID,
		arg.BaustelleID,
		arg.Von,
		arg.Bis,
	)
	var i AdminSumZeitbuchungRow
	err := row.Scan(&i.SummeMinuten, &i.Anzahl)
	return i, err
}

const adminSumZeitbuchungPerArbeiter = `-- name: AdminSumZeitbuchungPerArbeiter :many
SELECT
    arbeiter_id,
    COALESCE(SUM(
        CAST(EXTRACT(EPOCH FROM (end_zeit - start_zeit)) / 60 AS integer) - pause_minuten
    ), 0)::bigint AS summe_minuten,
    COUNT(*)::bigint AS anzahl
FROM zeitbuchung
WHERE end_zeit IS NOT NULL
  AND ($1::uuid  IS NULL OR arbeiter_id  = $1::uuid)
  AND ($2::uuid IS NULL OR baustelle_id = $2::uuid)
  AND ($3::timestamptz   IS NULL OR start_zeit  >= $3::timestamptz)
  AND ($4::timestamptz   IS NULL OR start_zeit  <  $4::timestamptz)
GROUP BY arbeiter_id
ORDER BY arbeiter_id
`

type AdminSumZeitbuchungPerArbeiterParams struct {
	ArbeiterID  *uuid.UUID `json:"arbeiter_id"`
	BaustelleID *uuid.UUID `json:"baustelle_id"`
	Von         *time.Time `json:"von"`
	Bis         *time.Time `json:"bis"`
}

type AdminSumZeitbuchungPerArbeiterRow struct {
	ArbeiterID   uuid.UUID `json:"arbeiter_id"`
	SummeMinuten int64     `json:"summe_minuten"`
	Anzahl       int64     `json:"anzahl"`
}

// Summe je Arbeiter. Gleiche Filter wie oben.
func (q *Queries) AdminSumZeitbuchungPerArbeiter(ctx context.Context, arg AdminSumZeitbuchungPerArbeiterParams) ([]AdminSumZeitbuchungPerArbeiterRow, error) {
	rows, err := q.db.Query(ctx, adminSumZeitbuchungPerArbeiter,
		arg.ArbeiterID,
		arg.BaustelleID,
		arg.Von,
		arg.Bis,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSumZeitbuchungPerArbeiterRow
	for rows.Next() {
		var i AdminSumZeitbuchungPerArbeiterRow
		if err := rows.Scan(&i.ArbeiterID, &i.SummeMinuten, &i.Anzahl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunningForArbeiter = `-- name: GetRunningForArbeiter :one
SELECT id, arbeiter_id, baustelle_id, start_zeit, end_zeit, pause_minuten, notiz, created_at, updated_at FROM zeitbuchung
WHERE arbeiter_id = $1 AND end_zeit IS NULL
`

// Die aktuell laufende Buchung (falls vorhanden). pgx.ErrNoRows => keine.
func (q *Queries) GetRunningForArbeiter(ctx context.Context, arbeiterID uuid.UUID) (Zeitbuchung, error) {
	row := q.db.QueryRow(ctx, getRunningForArbeiter, arbeiterID)
	var i Zeitbuchung
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.BaustelleID,
		&i.StartZeit,
		&i.EndZeit,
		&i.PauseMinuten,
		&i.Notiz,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getZeitbuchungByIDForArbeiter = `-- name: GetZeitbuchungByIDForArbeiter :one
SELECT id, arbeiter_id, baustelle_id, start_zeit, end_zeit, pause_minuten, notiz, created_at, updated_at FROM zeitbuchung
WHERE id = $1 AND arbeiter_id = $2
`

type GetZeitbuchungByIDForArbeiterParams struct {
	ID         uuid.UUID `json:"id"`
	ArbeiterID uuid.UUID `json:"arbeiter_id"`
}

// Ownership-Scope: liefert nur, wenn die Buchung dem Arbeiter gehört.
func (q *Queries) GetZeitbuchungByIDForArbeiter(ctx context.Context, arg GetZeitbuchungByIDForArbeiterParams) (Zeitbuchung, error) {
	row := q.db.QueryRow(ctx, getZeitbuchungByIDForArbeiter, arg.ID, arg.ArbeiterID)
	var i Zeitbuchung
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.BaustelleID,
		&i.StartZeit,
		&i.EndZeit,
		&i.PauseMinuten,
		&i.Notiz,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOwnZeitbuchung = `-- name: ListOwnZeitbuchung :many
SELECT id, arbeiter_id, baustelle_id, start_zeit, end_zeit, pause_minuten, notiz, created_at, updated_at FROM zeitbuchung
WHERE arbeiter_id = $1
  AND ($2::timestamptz IS NULL OR start_zeit >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR start_zeit <  $3::timestamptz)
ORDER BY start_zeit DESC
`

type ListOwnZeitbuchungParams struct {
	ArbeiterID uuid.UUID  `json:"arbeiter_id"`
	Von        *time.Time `json:"von"`
	Bis        *time.Time `json:"bis"`
}

// Eigene Buchungen, optionaler Zeitraum-Filter über start_zeit. Neueste zuerst.
func (q *Queries) ListOwnZeitbuchung(ctx context.Context, arg ListOwnZeitbuchungParams) ([]Zeitbuchung, error) {
	rows, err := q.db.Query(ctx, listOwnZeitbuchung, arg.ArbeiterID, arg.Von, arg.Bis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zeitbuchung
	for rows.Next() {
		var i Zeitbuchung
		if err := rows.Scan(
			&i.ID,
			&i.ArbeiterID,
			&i.BaustelleID,
			&i.StartZeit,
			&i.EndZeit,
			&i.PauseMinuten,
			&i.Notiz,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startZeitbuchung = `-- name: StartZeitbuchung :one
INSERT INTO zeitbuchung (id, arbeiter_id, baustelle_id, start_zeit, notiz)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, arbeiter_id, baustelle_id, start_zeit, end_zeit, pause_minuten, notiz, created_at, updated_at
`

type StartZeitbuchungParams struct {
	ID          uuid.UUID  `json:"id"`
	ArbeiterID  uuid.UUID  `json:"arbeiter_id"`
	BaustelleID *uuid.UUID `json:"baustelle_id"`
	StartZeit   time.Time  `json:"start_zeit"`
	Notiz       string     `json:"notiz"`
}

// Neue laufende Buchung (end_zeit NULL, pause Default 0). Verstößt gegen den
// Partial-Unique-Index, wenn bereits eine läuft -> 23505 (Handler -> 409).
func (q *Queries) StartZeitbuchung(ctx context.Context, arg StartZeitbuchungParams) (Zeitbuchung, error) {
	row := q.db.QueryRow(ctx, startZeitbuchung,
		arg.ID,
		arg.ArbeiterID,
		arg.BaustelleID,
		arg.StartZeit,
		arg.Notiz,
	)
	var i Zeitbuchung
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.BaustelleID,
		&i.StartZeit,
		&i.EndZeit,
		&i.PauseMinuten,
		&i.Notiz,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stopZeitbuchung = `-- name: StopZeitbuchung :one
UPDATE zeitbuchung
   SET end_zeit      = $1::timestamptz,
       pause_minuten = $2::integer,
       updated_at    = now()
 WHERE arbeiter_id = $3
   AND end_zeit IS NULL
RETURNING id, arbeiter_id, baustelle_id, start_zeit, end_zeit, pause_minuten, notiz, created_at, updated_at
`

type StopZeitbuchungParams struct {
	EndZeit      time.Time `json:"end_zeit"`
	PauseMinuten int32     `json:"pause_minuten"`
	ArbeiterID   uuid.UUID `json:"arbeiter_id"`
}

// Beendet die EINE laufende Buchung des Arbeiters. 0 Zeilen => keine laufende.
// pause_minuten wird app-seitig statutarisch berechnet (AZG §11) übergeben.
func (q *Queries) StopZeitbuchung(ctx context.Context, arg StopZeitbuchungParams) (Zeitbuchung, error) {
	row := q.db.QueryRow(ctx, stopZeitbuchung, arg.EndZeit, arg.PauseMinuten, arg.ArbeiterID)
	var i Zeitbuchung
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.BaustelleID,
		&i.StartZeit,
		&i.EndZeit,
		&i.PauseMinuten,
		&i.Notiz,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateZeitbuchung = `-- name: UpdateZeitbuchung :one
UPDATE zeitbuchung
   SET start_zeit    = COALESCE($1::timestamptz, start_zeit),
       end_zeit      = COALESCE($2::timestamptz,   end_zeit),
       baustelle_id  = COALESCE($3::uuid,      baustelle_id),
       pause_minuten = COALESCE($4::integer,  pause_minuten),
       notiz         = COALESCE($5::text,             notiz),
       updated_at    = now()
 WHERE id = $6 AND arbeiter_id = $7
RETURNING id, arbeiter_id, baustelle_id, start_zeit, end_zeit, pause_minuten, notiz, created_at, updated_at
`

type UpdateZeitbuchungParams struct {
	StartZeit    *time.Time `json:"start_zeit"`
	EndZeit      *time.Time `json:"end_zeit"`
	BaustelleID  *uuid.UUID `json:"baustelle_id"`
	PauseMinuten *int32     `json:"pause_minuten"`
	Notiz        *string    `json:"notiz"`
	ID           uuid.UUID  `json:"id"`
	ArbeiterID   uuid.UUID  `json:"arbeiter_id"`
}

// Partial update (COALESCE). Ownership-gescoped. Dauer-Prüfung app-seitig + DB-CHECK.
func (q *Queries) UpdateZeitbuchung(ctx context.Context, arg UpdateZeitbuchungParams) (Zeitbuchung, error) {
	row := q.db.QueryRow(ctx, updateZeitbuchung,
		arg.StartZeit,
		arg.EndZeit,
		arg.BaustelleID,
		arg.PauseMinuten,
		arg.Notiz,
		arg.ID,
		arg.ArbeiterID,
	)
	var i Zeitbuchung
	err := row.Scan(
		&i.ID,
		&i.ArbeiterID,
		&i.BaustelleID,
		&i.StartZeit,
		&i.EndZeit,
		&i.PauseMinuten,
		&i.Notiz,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
